version: "3.1"
services:
  messenger-hub-package:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: messenger-hub-package
    volumes:
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf

